#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib/common.sh
source "$ROOT_DIR/lib/common.sh"

print_header "Stackarr Init"

DB_FILE="${STACKARR_DATABASE_FILE:-$(default_stackarr_database_file)}"
if [[ -f "$DB_FILE" ]]; then
    warn "$DB_FILE already exists."
    confirm "Overwrite Stackarr runtime config in SQLite" no || exit 0
fi

DEFAULT_APP_ROOT="$(default_app_root)"
STACKARR_REPO_ROOT="$REPO_ROOT"
DEFAULT_MEDIA="$DEFAULT_APP_ROOT/media"
DEFAULT_DOWNLOADS="$DEFAULT_APP_ROOT/downloads"
DEFAULT_BACKUPS="$DEFAULT_APP_ROOT/backups"
DEFAULT_PLEX="$HOME/Library/Application Support/Plex Media Server"
DEFAULT_PLEX_PREFS="$HOME/Library/Preferences/com.plexapp.plexmediaserver.plist"
DEFAULT_TZ="Etc/UTC"

MEDIA_ROOT="$(prompt_default 'Media root' "$DEFAULT_MEDIA")"
DEFAULT_MUSIC="$MEDIA_ROOT/Music"
MUSIC_ROOT="$(prompt_default 'Music root' "$DEFAULT_MUSIC")"
DOWNLOADS_ROOT="$(prompt_default 'Downloads root' "$DEFAULT_DOWNLOADS")"
BACKUP_ROOT="$(prompt_default 'Backup root' "$DEFAULT_BACKUPS")"
PLEX_CONFIG_PATH="$(prompt_default 'Native Plex config path' "$DEFAULT_PLEX")"
PLEX_INSTALL_MODE="$(prompt_choice 'Plex install mode (docker, native, disabled)' 'native' 'docker' 'native' 'disabled')"
JELLYFIN_INSTALL_MODE="$(prompt_choice 'Jellyfin install mode (disabled, docker, native)' 'disabled' 'disabled' 'docker' 'native')"
JELLYFIN_CONFIG_PATH="$(prompt_default 'Native Jellyfin config path' "$HOME/.local/share/jellyfin")"
if confirm "Run separate Radarr/Sonarr 4K instances" no; then ENABLE_4K_SERVARR="true"; else ENABLE_4K_SERVARR="false"; fi
if confirm "Enable Bazarr subtitles" yes; then ENABLE_BAZARR="true"; else ENABLE_BAZARR="false"; fi
if confirm "Enable Lidarr music automation" yes; then ENABLE_LIDARR="true"; else ENABLE_LIDARR="false"; fi
if confirm "Enable BookOrbit books" no; then ENABLE_BOOKORBIT="true"; else ENABLE_BOOKORBIT="false"; fi
if confirm "Enable Immich photo library functionality" no; then ENABLE_IMMICH="true"; else ENABLE_IMMICH="false"; fi
if confirm "Enable RomM private game library functionality" no; then ENABLE_ROMM="true"; else ENABLE_ROMM="false"; fi
if confirm "Enable TinyMediaManager metadata/naming" yes; then ENABLE_TINYMEDIAMANAGER="true"; else ENABLE_TINYMEDIAMANAGER="false"; fi
if confirm "Enable Recyclarr profile sync" yes; then ENABLE_RECYCLARR="true"; else ENABLE_RECYCLARR="false"; fi
if confirm "Enable FlareSolverr indexer helper" yes; then ENABLE_FLARESOLVERR="true"; else ENABLE_FLARESOLVERR="false"; fi
if confirm "Enable Tidarr Tidal helper" yes; then ENABLE_TIDARR="true"; else ENABLE_TIDARR="false"; fi
if confirm "Enable Seerr requests" no; then ENABLE_SEERR="true"; else ENABLE_SEERR="false"; fi
if flag_enabled "$ENABLE_SEERR" && confirm "Wire Seerr to Radarr/Sonarr automatically" no; then STACKARR_CONFIGURE_SEERR="true"; else STACKARR_CONFIGURE_SEERR="false"; fi
if confirm "Enable Pulsarr Plex watchlists" yes; then ENABLE_PULSARR="true"; else ENABLE_PULSARR="false"; fi
if confirm "Enable Maintainerr cleanup planner" no; then
    ENABLE_MAINTAINERR="true"
    MAINTAINERR_CLEANUP_PRESETS="$(prompt_default 'Maintainerr cleanup preset ideas (comma-separated, blank for none)' '')"
else
    ENABLE_MAINTAINERR="false"
    MAINTAINERR_CLEANUP_PRESETS=""
fi
if confirm "Enable Tracearr media-server monitoring" no; then ENABLE_TRACEARR="true"; else ENABLE_TRACEARR="false"; fi
USERNAME="$(prompt_default 'Global service username' 'admin')"
while true; do
    PASSWORD="$(prompt_secret_default 'Global service password (blank generates one)' '')"
    if [[ -z "$PASSWORD" ]] || password_is_portable "$PASSWORD"; then
        break
    fi
    warn "Global service password must be at least 8 characters and may only use letters, numbers, dot, underscore, and hyphen."
done
USER_EMAIL="$(prompt_default 'Global service email (blank uses Plex account email when available)' '')"
ROMM_LIBRARY_ROOT_INPUT=""
ROMM_METADATA_PRESET="chef"
ROMM_IGDB_CLIENT_ID=""
ROMM_IGDB_CLIENT_SECRET=""
ROMM_STEAMGRIDDB_API_KEY=""
ROMM_RETROACHIEVEMENTS_API_KEY=""
ROMM_SCREENSCRAPER_USER=""
ROMM_SCREENSCRAPER_PASSWORD=""
ROMM_HASHEOUS_API_ENABLED="true"
ROMM_PLAYMATCH_API_ENABLED="false"
if flag_enabled "$ENABLE_ROMM"; then
    ROMM_LIBRARY_ROOT_INPUT="$(prompt_default 'RomM library root' "$MEDIA_ROOT/Games")"
    ROMM_METADATA_PRESET="$(prompt_choice 'RomM metadata providers (chef, french, twitch, quick, custom)' 'chef' 'chef' 'french' 'twitch' 'quick' 'custom')"
    case "$ROMM_METADATA_PRESET" in
        chef|twitch|custom)
            ROMM_IGDB_CLIENT_ID="$(prompt_default 'RomM IGDB client ID (blank to skip)' '')"
            ROMM_IGDB_CLIENT_SECRET="$(prompt_secret_default 'RomM IGDB client secret (blank to skip)' '')"
            ;;
    esac
    case "$ROMM_METADATA_PRESET" in
        chef|custom)
            ROMM_STEAMGRIDDB_API_KEY="$(prompt_secret_default 'RomM SteamGridDB API key (blank to skip)' '')"
            ;;
    esac
    case "$ROMM_METADATA_PRESET" in
        chef|french|custom)
            ROMM_RETROACHIEVEMENTS_API_KEY="$(prompt_secret_default 'RomM RetroAchievements API key (blank to skip)' '')"
            ;;
    esac
    case "$ROMM_METADATA_PRESET" in
        french|custom)
            ROMM_SCREENSCRAPER_USER="$(prompt_default 'RomM ScreenScraper username (blank to skip)' '')"
            ROMM_SCREENSCRAPER_PASSWORD="$(prompt_secret_default 'RomM ScreenScraper password (blank to skip)' '')"
            ;;
    esac
    case "$ROMM_METADATA_PRESET" in
        quick|chef)
            ROMM_HASHEOUS_API_ENABLED="true"
            ROMM_PLAYMATCH_API_ENABLED="false"
            ;;
        twitch)
            ROMM_HASHEOUS_API_ENABLED="false"
            ROMM_PLAYMATCH_API_ENABLED="true"
            ;;
    esac
fi
STACKARR_DATABASE_MODE="$(prompt_choice 'Advanced database mode for supported apps (app-default or postgres)' 'app-default' 'app-default' 'postgres')"
TIMEZONE="$(prompt_default 'Timezone' "$DEFAULT_TZ")"
SEERR_BIND_IP="$(prompt_default 'Seerr bind IP (0.0.0.0 for LAN, 127.0.0.1 for tunnel-only)' '0.0.0.0')"
TRANSMISSION_BIND_IP="$(prompt_default 'Transmission Web UI bind IP (0.0.0.0 for LAN, 127.0.0.1 for localhost-only)' '127.0.0.1')"
QBITTORRENT_BIND_IP="$(prompt_default 'qBittorrent Web UI bind IP (0.0.0.0 for LAN, 127.0.0.1 for localhost-only)' '127.0.0.1')"
PREFERRED_TORRENT_CLIENT="$(prompt_choice 'Preferred torrent client (transmission or qbittorrent)' 'transmission' 'transmission' 'qbittorrent')"
BACKUP_TIME="$(prompt_default 'Backup time (HH:MM)' '02:00')"
BACKUP_SCHEDULE="weekly"
BACKUP_WEEKDAY="Sun"
BACKUP_RETENTION_COUNT="$(prompt_default 'Backup retention count (latest archives to keep)' '52')"
ENABLE_BACKUP="true"
ENABLE_SCHEDULED_UPDATES="false"

PUID="$(id -u)"
PGID="$(id -g)"
APP_ROOT="$DEFAULT_APP_ROOT"
CONFIG_ROOT="$APP_ROOT/config"
STATE_ROOT="$APP_ROOT/state"
LOG_ROOT="$APP_ROOT/logs"
PLEX_PREFS_PATH="$DEFAULT_PLEX_PREFS"
if [[ -z "$PASSWORD" ]]; then
    PASSWORD="$(random_secret 20)"
fi
STACKARR_API_KEY="$(random_secret 48)"
STACKARR_DOCKER_CONTEXT="${STACKARR_DOCKER_CONTEXT:-}"
DATABASE_IMAGE="timescale/timescaledb-ha:pg18.1-ts2.25.0"
DATABASE_PGDATA="/var/lib/postgresql/data"
DATABASE_BIND_IP="127.0.0.1"
DATABASE_HOST_PORT="5433"
DATABASE_NAME="postgres"
DATABASE_SUPERUSER="postgres"
DATABASE_SUPERUSER_PASSWORD="$(random_secret 24)"
STACKARR_POSTGRES_MAIN_DATABASE="stackarr-main"
STACKARR_POSTGRES_DATABASE="$STACKARR_POSTGRES_MAIN_DATABASE"
STACKARR_POSTGRES_LOG_DATABASE="stackarr-log"
STACKARR_POSTGRES_USER="stackarr"
STACKARR_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
if [[ "$STACKARR_DATABASE_MODE" == "postgres" ]]; then
    STACKARR_DATABASE_URL="postgres://$(urlencode_component "$STACKARR_POSTGRES_USER"):$(urlencode_component "$STACKARR_POSTGRES_PASSWORD")@database:5432/$(urlencode_component "$STACKARR_POSTGRES_DATABASE")"
    STACKARR_LOG_DATABASE_URL="postgres://$(urlencode_component "$STACKARR_POSTGRES_USER"):$(urlencode_component "$STACKARR_POSTGRES_PASSWORD")@database:5432/$(urlencode_component "$STACKARR_POSTGRES_LOG_DATABASE")"
else
    STACKARR_DATABASE_URL=""
    STACKARR_LOG_DATABASE_URL=""
fi
BOOKORBIT_POSTGRES_DATABASE="bookorbit"
BOOKORBIT_POSTGRES_USER="bookorbit"
BOOKORBIT_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
BOOKORBIT_DATABASE_URL="postgres://$(urlencode_component "$BOOKORBIT_POSTGRES_USER"):$(urlencode_component "$BOOKORBIT_POSTGRES_PASSWORD")@database:5432/$(urlencode_component "$BOOKORBIT_POSTGRES_DATABASE")"
IMMICH_DB_USERNAME="immich"
IMMICH_DB_DATABASE_NAME="immich"
IMMICH_DB_PASSWORD=""
IMMICH_DB_VECTOR_EXTENSION="pgvector"
if flag_enabled "$ENABLE_IMMICH"; then
    IMMICH_DB_PASSWORD="$(random_secret 24)"
fi
GAMES_ROOT="${ROMM_LIBRARY_ROOT_INPUT:-$MEDIA_ROOT/Games}"
ROMM_BIND_IP="127.0.0.1"
ROMM_WEB_PORT="7583"
ROMM_CONTAINER_PORT="8080"
ROMM_URL="http://127.0.0.1:$ROMM_WEB_PORT"
ROMM_LIBRARY_ROOT="$GAMES_ROOT"
ROMM_ASSETS_ROOT="$CONFIG_ROOT/romm/assets"
ROMM_CONFIG_ROOT="$CONFIG_ROOT/romm/config"
ROMM_RESOURCES_ROOT="$CONFIG_ROOT/romm/resources"
ROMM_REDIS_DATA_ROOT="$CONFIG_ROOT/romm/redis"
ROMM_REDIS_HOST="redis"
ROMM_REDIS_PORT="6379"
ROMM_DB_DATA_LOCATION="$CONFIG_ROOT/romm/mysql"
ROMM_DB_DRIVER="postgresql"
ROMM_DB_HOST="database"
ROMM_DB_PORT="5432"
ROMM_DB_NAME="romm"
ROMM_DB_USER="romm"
ROMM_DB_PASSWORD=""
ROMM_DB_ROOT_PASSWORD=""
ROMM_DB_QUERY_JSON=""
ROMM_AUTH_SECRET_KEY=""
ROMM_AUTO_CONFIGURE="false"
ROMM_ADMIN_USERNAME=""
ROMM_ADMIN_EMAIL=""
ROMM_ADMIN_PASSWORD=""
ROMM_MOBYGAMES_API_KEY=""
ROMM_LAUNCHBOX_API_ENABLED="false"
ROMM_FLASHPOINT_API_ENABLED="false"
ROMM_HLTB_API_ENABLED="false"
if flag_enabled "$ENABLE_ROMM"; then
    ROMM_DB_PASSWORD="$(random_secret 24)"
    ROMM_AUTH_SECRET_KEY="$(random_secret 32)"
fi
SEERR_POSTGRES_DATABASE="seerr"
SEERR_POSTGRES_USER="seerr"
SEERR_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
PULSARR_POSTGRES_DATABASE="pulsarr"
PULSARR_POSTGRES_USER="pulsarr"
PULSARR_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
if [[ "$STACKARR_DATABASE_MODE" == "postgres" ]]; then
    PULSARR_DB_TYPE="postgres"
    PULSARR_DB_HOST="database"
    PULSARR_DB_PORT="5432"
    PULSARR_DB_NAME="$PULSARR_POSTGRES_DATABASE"
    PULSARR_DB_USER="$PULSARR_POSTGRES_USER"
    PULSARR_DB_PASSWORD="$PULSARR_POSTGRES_PASSWORD"
    BAZARR_POSTGRES_ENABLED="true"
    BAZARR_POSTGRES_HOST="database"
    BAZARR_POSTGRES_PORT="5432"
    PROWLARR_POSTGRES_HOST="database"
    PROWLARR_POSTGRES_PORT="5432"
    RADARR_POSTGRES_HOST="database"
    RADARR_POSTGRES_PORT="5432"
    RADARR4K_POSTGRES_HOST="database"
    RADARR4K_POSTGRES_PORT="5432"
    SONARR_POSTGRES_HOST="database"
    SONARR_POSTGRES_PORT="5432"
    SONARR4K_POSTGRES_HOST="database"
    SONARR4K_POSTGRES_PORT="5432"
    LIDARR_POSTGRES_HOST="database"
    LIDARR_POSTGRES_PORT="5432"
else
    PULSARR_DB_TYPE="sqlite"
    PULSARR_DB_HOST=""
    PULSARR_DB_PORT="5432"
    PULSARR_DB_NAME=""
    PULSARR_DB_USER=""
    PULSARR_DB_PASSWORD=""
    BAZARR_POSTGRES_ENABLED="false"
    BAZARR_POSTGRES_HOST=""
    BAZARR_POSTGRES_PORT=""
    PROWLARR_POSTGRES_HOST=""
    PROWLARR_POSTGRES_PORT=""
    RADARR_POSTGRES_HOST=""
    RADARR_POSTGRES_PORT=""
    RADARR4K_POSTGRES_HOST=""
    RADARR4K_POSTGRES_PORT=""
    SONARR_POSTGRES_HOST=""
    SONARR_POSTGRES_PORT=""
    SONARR4K_POSTGRES_HOST=""
    SONARR4K_POSTGRES_PORT=""
    LIDARR_POSTGRES_HOST=""
    LIDARR_POSTGRES_PORT=""
fi
PULSARR_DB_PATH="/app/data/db/pulsarr.db"
SEERR_DB_TYPE="postgres"
BAZARR_POSTGRES_DATABASE="bazarr"
BAZARR_POSTGRES_USER="bazarr"
BAZARR_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
PROWLARR_POSTGRES_MAIN_DATABASE="prowlarr-main"
PROWLARR_POSTGRES_LOG_DATABASE="prowlarr-log"
PROWLARR_POSTGRES_USER="prowlarr"
PROWLARR_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
RADARR_POSTGRES_MAIN_DATABASE="radarr-main"
RADARR_POSTGRES_LOG_DATABASE="radarr-log"
RADARR_POSTGRES_USER="radarr"
RADARR_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
RADARR4K_POSTGRES_MAIN_DATABASE="radarr4k-main"
RADARR4K_POSTGRES_LOG_DATABASE="radarr4k-log"
RADARR4K_POSTGRES_USER="radarr4k"
RADARR4K_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
SONARR_POSTGRES_MAIN_DATABASE="sonarr-main"
SONARR_POSTGRES_LOG_DATABASE="sonarr-log"
SONARR_POSTGRES_USER="sonarr"
SONARR_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
SONARR4K_POSTGRES_MAIN_DATABASE="sonarr4k-main"
SONARR4K_POSTGRES_LOG_DATABASE="sonarr4k-log"
SONARR4K_POSTGRES_USER="sonarr4k"
SONARR4K_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
LIDARR_POSTGRES_MAIN_DATABASE="lidarr-main"
LIDARR_POSTGRES_LOG_DATABASE="lidarr-log"
LIDARR_POSTGRES_USER="lidarr"
LIDARR_POSTGRES_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"

# BookOrbit secrets are generated only when the optional service is enabled.
if flag_enabled "$ENABLE_BOOKORBIT"; then
    BOOKORBIT_JWT_SECRET="$(random_secret 32)"
    BOOKORBIT_SETUP_TOKEN="$PASSWORD"
fi

DOWNLOAD_INCOMPLETE_NAME="incomplete"
DOWNLOAD_COMPLETE_NAME="complete"
TRANSMISSION_TORRENT_PORT="51413"
TRANSMISSION_URL="http://127.0.0.1:9091"
QBITTORRENT_URL="http://127.0.0.1:8081"
PROWLARR_URL="http://127.0.0.1:9696"
RADARR_URL="http://127.0.0.1:7878"
RADARR_4K_URL="http://127.0.0.1:7879"
RADARR4K_URL="$RADARR_4K_URL"
SONARR_URL="http://127.0.0.1:8989"
SONARR_4K_URL="http://127.0.0.1:8990"
SONARR4K_URL="$SONARR_4K_URL"
LIDARR_URL="http://127.0.0.1:8686"
BOOKORBIT_BIND_IP="127.0.0.1"
BOOKORBIT_WEB_PORT="7582"
BOOKORBIT_CONTAINER_PORT="7582"
BOOKORBIT_URL="http://127.0.0.1:$BOOKORBIT_WEB_PORT"
BOOKORBIT_APP_URL="$BOOKORBIT_URL"
BOOKORBIT_CLIENT_URL="$BOOKORBIT_URL"
BOOKS_ROOT="$MEDIA_ROOT/Books"
IMMICH_BIND_IP="127.0.0.1"
IMMICH_WEB_PORT="2283"
IMMICH_CONTAINER_PORT="2283"
IMMICH_URL="http://127.0.0.1:$IMMICH_WEB_PORT"
IMMICH_UPLOAD_LOCATION="$MEDIA_ROOT/Pictures"
IMMICH_VERSION="release"
BAZARR_URL="http://127.0.0.1:6767"
SEERR_URL="http://127.0.0.1:5055"
PULSARR_URL="http://127.0.0.1:3003"
MAINTAINERR_URL="http://127.0.0.1:6246"
TRACEARR_URL="http://127.0.0.1:3000"
PLEX_URL="http://127.0.0.1:32400"
JELLYFIN_URL="http://127.0.0.1:8096"
TINYMEDIAMANAGER_URL="http://127.0.0.1:4000"
FLARESOLVERR_URL="http://127.0.0.1:8191"
PROWLARR_API_KEY=""
RADARR_API_KEY=""
RADARR4K_API_KEY=""
SONARR_API_KEY=""
SONARR4K_API_KEY=""
LIDARR_API_KEY=""
SEERR_API_KEY=""
PLEX_TOKEN=""
JELLYFIN_API_KEY=""
RADARR_CATEGORY="radarr"
RADARR_4K_CATEGORY="radarr-uhd"
SONARR_CATEGORY="tv-sonarr"
SONARR_4K_CATEGORY="tv-sonarr-uhd"
LIDARR_CATEGORY="lidarr"
PLEX_BACKUP_MODE="lite"
STACKARR_STORAGE_WAIT_SECONDS="600"
UPDATE_TIME="04:30"
UPDATE_WEEKDAY="Sun"
STACKARR_WEB_ENABLED="true"
STACKARR_IMAGE="polyphonic/stackarr:alpha"
STACKARR_BIND_IP="127.0.0.1"
STACKARR_WEB_PORT="7777"
STACKARR_TELEMETRY_FEATURE_ENABLED="false"
STACKARR_TELEMETRY_ENABLED="false"
STACKARR_TELEMETRY_ENDPOINT=""
STACKARR_TELEMETRY_CHANNEL="stable"
STACKARR_TELEMETRY_INGEST_KEY=""
TRANSMISSION_IMAGE="lscr.io/linuxserver/transmission:latest"
QBITTORRENT_IMAGE="lscr.io/linuxserver/qbittorrent:latest"
QBITTORRENT_WEBUI_PORT="8081"
QBITTORRENT_TORRENT_PORT="6881"
RADARR_IMAGE="lscr.io/linuxserver/radarr:latest"
SONARR_IMAGE="lscr.io/linuxserver/sonarr:latest"
PROWLARR_IMAGE="lscr.io/linuxserver/prowlarr:latest"
BAZARR_IMAGE="lscr.io/linuxserver/bazarr:latest"
SEERR_IMAGE="ghcr.io/seerr-team/seerr:latest"
PULSARR_IMAGE="lakker/pulsarr:latest"
PULSARR_PORT="3003"
PULSARR_AUTHENTICATION_METHOD="requiredExceptLocal"
PULSARR_COOKIE_SECURED="false"
MAINTAINERR_IMAGE="ghcr.io/maintainerr/maintainerr:latest"
MAINTAINERR_BIND_IP="127.0.0.1"
MAINTAINERR_PORT="6246"
MAINTAINERR_BASE_PATH=""
MAINTAINERR_GITHUB_TOKEN=""
MAINTAINERR_PLEX_SERVER_URL=""
MAINTAINERR_JELLYFIN_SERVER_URL=""
MAINTAINERR_QBITTORRENT_URL=""
TRACEARR_IMAGE="ghcr.io/connorgallopo/tracearr:latest"
REDIS_IMAGE="redis:8.8.0-alpine"
TRACEARR_BIND_IP="127.0.0.1"
TRACEARR_PORT="3000"
TRACEARR_AUTO_CONFIGURE="true"
TRACEARR_ADMIN_USERNAME="$USERNAME"
TRACEARR_ADMIN_EMAIL="$USER_EMAIL"
TRACEARR_ADMIN_PASSWORD=""
TRACEARR_CLAIM_CODE=""
TRACEARR_PLEX_SERVER_URL=""
TRACEARR_JELLYFIN_SERVER_URL=""
TRACEARR_EMBY_SERVER_URL=""
TRACEARR_DB_PASSWORD="$DATABASE_SUPERUSER_PASSWORD"
TRACEARR_POSTGRES_DATABASE="tracearr"
TRACEARR_POSTGRES_USER="tracearr"
TRACEARR_POSTGRES_PASSWORD="$TRACEARR_DB_PASSWORD"
TRACEARR_JWT_SECRET=""
TRACEARR_COOKIE_SECRET=""
TRACEARR_LOG_LEVEL="info"
TRACEARR_CORS_ORIGIN="*"
if flag_enabled "$ENABLE_TRACEARR"; then
    TRACEARR_JWT_SECRET="$(random_hex_secret 32)"
    TRACEARR_COOKIE_SECRET="$(random_hex_secret 32)"
    TRACEARR_ADMIN_PASSWORD="$PASSWORD"
fi
RECYCLARR_IMAGE="ghcr.io/recyclarr/recyclarr:latest"
FLARESOLVERR_IMAGE="ghcr.io/flaresolverr/flaresolverr:latest"
LIDARR_IMAGE="lscr.io/linuxserver/lidarr:latest"
TIDARR_IMAGE="cstaelen/tidarr:latest"
BOOKORBIT_IMAGE="ghcr.io/bookorbit/bookorbit:latest"
IMMICH_SERVER_IMAGE="ghcr.io/immich-app/immich-server"
IMMICH_MACHINE_LEARNING_IMAGE="ghcr.io/immich-app/immich-machine-learning"
ROMM_IMAGE="rommapp/romm:latest"
ROMM_DB_IMAGE=""
TINYMEDIAMANAGER_IMAGE="tinymediamanager/tinymediamanager:latest"
PLEX_IMAGE="lscr.io/linuxserver/plex:latest"
PLEX_DOCKER_PORT="32400"
JELLYFIN_IMAGE="lscr.io/linuxserver/jellyfin:latest"
JELLYFIN_DOCKER_PORT="8096"
CLOUDFLARE_API_TOKEN=""
CLOUDFLARE_ACCOUNT_ID=""
CLOUDFLARE_ZONE_ID=""
CLOUDFLARED_TUNNEL_NAME="stackarr"
CLOUDFLARED_TUNNEL_ID=""
CLOUDFLARED_METRICS_PORT="42183"
CLOUDFLARED_BIN=""
CLOUDFLARED_TOKEN_FILE=""
CLOUDFLARED_KEEP_LAN="true"
CLOUDFLARE_ROUTE_MANAGED="false"
CLOUDFLARE_TUNNEL_ROUTES=""
CLOUDFLARE_ACCESS_ENABLED="false"
CLOUDFLARE_ACCESS_ALLOWED_EMAILS=""
CLOUDFLARE_ACCESS_SESSION_DURATION="720h"
SEERR_ORIGIN_URL="http://127.0.0.1:5055"

ensure_dir "$MEDIA_ROOT/Movies"
ensure_dir "$MEDIA_ROOT/TV Shows"
ensure_dir "$MUSIC_ROOT"
if flag_enabled "$ENABLE_BOOKORBIT"; then
    ensure_dir "$BOOKS_ROOT"
fi
if flag_enabled "$ENABLE_IMMICH"; then
    ensure_dir "$IMMICH_UPLOAD_LOCATION"
fi
if flag_enabled "$ENABLE_ROMM"; then
    ensure_dir "$ROMM_LIBRARY_ROOT"
    ensure_dir "$ROMM_ASSETS_ROOT"
    ensure_dir "$ROMM_CONFIG_ROOT"
    ensure_dir "$ROMM_RESOURCES_ROOT"
fi
ensure_dir "$CONFIG_ROOT/hooks"
ensure_dir "$CONFIG_ROOT/transmission"
ensure_dir "$CONFIG_ROOT/transmission/torrents"
ensure_dir "$CONFIG_ROOT/qbittorrent"
ensure_dir "$CONFIG_ROOT/qbittorrent/qBittorrent"
ensure_dir "$CONFIG_ROOT/qbittorrent/qBittorrent/BT_backup"
ensure_dir "$CONFIG_ROOT/radarr"
ensure_dir "$CONFIG_ROOT/sonarr"
if flag_enabled "$ENABLE_4K_SERVARR"; then
    ensure_dir "$CONFIG_ROOT/radarr4k"
    ensure_dir "$CONFIG_ROOT/sonarr4k"
fi
ensure_dir "$CONFIG_ROOT/prowlarr"
ensure_dir "$CONFIG_ROOT/bazarr"
ensure_dir "$CONFIG_ROOT/tinymediamanager"
ensure_dir "$CONFIG_ROOT/tinymediamanager/addons"
ensure_dir "$CONFIG_ROOT/seerr"
if flag_enabled "$ENABLE_MAINTAINERR"; then
    ensure_dir "$CONFIG_ROOT/maintainerr"
fi
if flag_enabled "$ENABLE_TRACEARR"; then
    ensure_dir "$CONFIG_ROOT/tracearr/backups"
fi
ensure_dir "$CONFIG_ROOT/recyclarr"
ensure_dir "$CONFIG_ROOT/recyclarr/configs"
ensure_dir "$CONFIG_ROOT/lidarr"
if flag_enabled "$ENABLE_BOOKORBIT"; then
    ensure_dir "$CONFIG_ROOT/bookorbit/app"
fi
if flag_enabled "$ENABLE_IMMICH"; then
    ensure_dir "$CONFIG_ROOT/immich"
fi
if flag_enabled "$ENABLE_ROMM"; then
    ensure_dir "$CONFIG_ROOT/romm"
fi
ensure_dir "$CONFIG_ROOT/tidarr"
ensure_dir "$CONFIG_ROOT/plex"
ensure_dir "$CONFIG_ROOT/jellyfin"
ensure_dir "$STATE_ROOT"
ensure_dir "$STATE_ROOT/torrent-archive/Movies"
ensure_dir "$STATE_ROOT/torrent-archive/TV Shows"
ensure_dir "$LOG_ROOT/launchd"
ensure_dir "$DOWNLOADS_ROOT/$DOWNLOAD_INCOMPLETE_NAME"
ensure_dir "$DOWNLOADS_ROOT/$DOWNLOAD_COMPLETE_NAME/$RADARR_CATEGORY"
ensure_dir "$DOWNLOADS_ROOT/$DOWNLOAD_COMPLETE_NAME/$SONARR_CATEGORY"
ensure_dir "$DOWNLOADS_ROOT/$DOWNLOAD_COMPLETE_NAME/$LIDARR_CATEGORY"
if flag_enabled "$ENABLE_4K_SERVARR"; then
    ensure_dir "$DOWNLOADS_ROOT/$DOWNLOAD_COMPLETE_NAME/$RADARR_4K_CATEGORY"
    ensure_dir "$DOWNLOADS_ROOT/$DOWNLOAD_COMPLETE_NAME/$SONARR_4K_CATEGORY"
fi
ensure_dir "$DOWNLOADS_ROOT/watch"
ensure_dir "$BACKUP_ROOT"

if [[ -d "$PLEX_CONFIG_PATH" ]] && is_subpath "$BACKUP_ROOT" "$PLEX_CONFIG_PATH"; then
    fail "Backup root must live outside the Plex Media Server data directory"
fi

export STACKARR_REPO_ROOT TIMEZONE PUID PGID MEDIA_ROOT MUSIC_ROOT DOWNLOADS_ROOT BACKUP_ROOT APP_ROOT CONFIG_ROOT STATE_ROOT LOG_ROOT PLEX_CONFIG_PATH PLEX_PREFS_PATH PLEX_INSTALL_MODE JELLYFIN_INSTALL_MODE JELLYFIN_CONFIG_PATH ENABLE_4K_SERVARR ENABLE_BAZARR ENABLE_LIDARR ENABLE_BOOKORBIT ENABLE_IMMICH ENABLE_ROMM ENABLE_TINYMEDIAMANAGER ENABLE_RECYCLARR ENABLE_FLARESOLVERR ENABLE_TIDARR ENABLE_SEERR STACKARR_CONFIGURE_SEERR ENABLE_PULSARR ENABLE_TRACEARR ENABLE_BACKUP USERNAME PASSWORD USER_EMAIL PREFERRED_TORRENT_CLIENT SEERR_BIND_IP PULSARR_BIND_IP PULSARR_PORT PULSARR_AUTHENTICATION_METHOD PULSARR_COOKIE_SECURED TRACEARR_BIND_IP TRACEARR_PORT TRACEARR_AUTO_CONFIGURE TRACEARR_ADMIN_USERNAME TRACEARR_ADMIN_EMAIL TRACEARR_ADMIN_PASSWORD TRACEARR_CLAIM_CODE TRACEARR_PLEX_SERVER_URL TRACEARR_JELLYFIN_SERVER_URL TRACEARR_EMBY_SERVER_URL TRACEARR_DB_PASSWORD TRACEARR_POSTGRES_DATABASE TRACEARR_POSTGRES_USER TRACEARR_POSTGRES_PASSWORD TRACEARR_JWT_SECRET TRACEARR_COOKIE_SECRET TRACEARR_LOG_LEVEL TRACEARR_CORS_ORIGIN TRANSMISSION_BIND_IP TRANSMISSION_URL TRANSMISSION_TORRENT_PORT QBITTORRENT_BIND_IP QBITTORRENT_URL QBITTORRENT_WEBUI_PORT QBITTORRENT_TORRENT_PORT PROWLARR_URL PROWLARR_API_KEY RADARR_URL RADARR_API_KEY RADARR_4K_URL RADARR4K_URL RADARR4K_API_KEY SONARR_URL SONARR_API_KEY SONARR_4K_URL SONARR4K_URL SONARR4K_API_KEY LIDARR_URL LIDARR_API_KEY BOOKORBIT_URL BOOKORBIT_APP_URL BOOKORBIT_CLIENT_URL BOOKORBIT_BIND_IP BOOKORBIT_WEB_PORT BOOKORBIT_CONTAINER_PORT BOOKS_ROOT DATABASE_IMAGE DATABASE_PGDATA DATABASE_BIND_IP DATABASE_HOST_PORT DATABASE_NAME DATABASE_SUPERUSER DATABASE_SUPERUSER_PASSWORD REDIS_IMAGE STACKARR_POSTGRES_DATABASE STACKARR_POSTGRES_MAIN_DATABASE STACKARR_POSTGRES_LOG_DATABASE STACKARR_POSTGRES_USER STACKARR_POSTGRES_PASSWORD STACKARR_DATABASE_URL STACKARR_LOG_DATABASE_URL BOOKORBIT_POSTGRES_DATABASE BOOKORBIT_POSTGRES_USER BOOKORBIT_POSTGRES_PASSWORD SEERR_POSTGRES_DATABASE SEERR_POSTGRES_USER SEERR_POSTGRES_PASSWORD PULSARR_POSTGRES_DATABASE PULSARR_POSTGRES_USER PULSARR_POSTGRES_PASSWORD BOOKORBIT_JWT_SECRET BOOKORBIT_SETUP_TOKEN BAZARR_URL SEERR_URL SEERR_API_KEY PULSARR_URL TRACEARR_URL PLEX_URL PLEX_TOKEN JELLYFIN_URL JELLYFIN_API_KEY TINYMEDIAMANAGER_URL FLARESOLVERR_URL BACKUP_TIME BACKUP_SCHEDULE BACKUP_WEEKDAY BACKUP_RETENTION_COUNT ENABLE_SCHEDULED_UPDATES UPDATE_TIME UPDATE_WEEKDAY PLEX_BACKUP_MODE STACKARR_STORAGE_WAIT_SECONDS STACKARR_API_KEY STACKARR_DOCKER_CONTEXT STACKARR_WEB_ENABLED STACKARR_IMAGE STACKARR_BIND_IP STACKARR_WEB_PORT STACKARR_TELEMETRY_FEATURE_ENABLED STACKARR_TELEMETRY_ENABLED STACKARR_TELEMETRY_ENDPOINT STACKARR_TELEMETRY_CHANNEL STACKARR_TELEMETRY_INGEST_KEY DOWNLOAD_INCOMPLETE_NAME DOWNLOAD_COMPLETE_NAME RADARR_CATEGORY RADARR_4K_CATEGORY SONARR_CATEGORY SONARR_4K_CATEGORY LIDARR_CATEGORY BOOKORBIT_IMAGE TRANSMISSION_IMAGE QBITTORRENT_IMAGE RADARR_IMAGE SONARR_IMAGE PROWLARR_IMAGE BAZARR_IMAGE SEERR_IMAGE PULSARR_IMAGE TRACEARR_IMAGE RECYCLARR_IMAGE FLARESOLVERR_IMAGE LIDARR_IMAGE TIDARR_IMAGE TINYMEDIAMANAGER_IMAGE PLEX_IMAGE PLEX_DOCKER_PORT JELLYFIN_IMAGE JELLYFIN_DOCKER_PORT CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_ZONE_ID CLOUDFLARED_TUNNEL_NAME CLOUDFLARED_TUNNEL_ID CLOUDFLARED_METRICS_PORT CLOUDFLARED_BIN CLOUDFLARED_TOKEN_FILE CLOUDFLARED_KEEP_LAN CLOUDFLARE_ROUTE_MANAGED CLOUDFLARE_TUNNEL_ROUTES CLOUDFLARE_ACCESS_ENABLED CLOUDFLARE_ACCESS_ALLOWED_EMAILS CLOUDFLARE_ACCESS_SESSION_DURATION SEERR_ORIGIN_URL
export STACKARR_DATABASE_MODE BOOKORBIT_DATABASE_URL SEERR_DB_TYPE PULSARR_DB_TYPE PULSARR_DB_PATH PULSARR_DB_HOST PULSARR_DB_PORT PULSARR_DB_NAME PULSARR_DB_USER PULSARR_DB_PASSWORD BAZARR_POSTGRES_ENABLED BAZARR_POSTGRES_HOST BAZARR_POSTGRES_PORT BAZARR_POSTGRES_DATABASE BAZARR_POSTGRES_USER BAZARR_POSTGRES_PASSWORD PROWLARR_POSTGRES_HOST PROWLARR_POSTGRES_PORT PROWLARR_POSTGRES_MAIN_DATABASE PROWLARR_POSTGRES_LOG_DATABASE PROWLARR_POSTGRES_USER PROWLARR_POSTGRES_PASSWORD RADARR_POSTGRES_HOST RADARR_POSTGRES_PORT RADARR_POSTGRES_MAIN_DATABASE RADARR_POSTGRES_LOG_DATABASE RADARR_POSTGRES_USER RADARR_POSTGRES_PASSWORD RADARR4K_POSTGRES_HOST RADARR4K_POSTGRES_PORT RADARR4K_POSTGRES_MAIN_DATABASE RADARR4K_POSTGRES_LOG_DATABASE RADARR4K_POSTGRES_USER RADARR4K_POSTGRES_PASSWORD SONARR_POSTGRES_HOST SONARR_POSTGRES_PORT SONARR_POSTGRES_MAIN_DATABASE SONARR_POSTGRES_LOG_DATABASE SONARR_POSTGRES_USER SONARR_POSTGRES_PASSWORD SONARR4K_POSTGRES_HOST SONARR4K_POSTGRES_PORT SONARR4K_POSTGRES_MAIN_DATABASE SONARR4K_POSTGRES_LOG_DATABASE SONARR4K_POSTGRES_USER SONARR4K_POSTGRES_PASSWORD LIDARR_POSTGRES_HOST LIDARR_POSTGRES_PORT LIDARR_POSTGRES_MAIN_DATABASE LIDARR_POSTGRES_LOG_DATABASE LIDARR_POSTGRES_USER LIDARR_POSTGRES_PASSWORD
export ENABLE_MAINTAINERR MAINTAINERR_URL MAINTAINERR_IMAGE MAINTAINERR_BIND_IP MAINTAINERR_PORT MAINTAINERR_BASE_PATH MAINTAINERR_GITHUB_TOKEN MAINTAINERR_CLEANUP_PRESETS MAINTAINERR_PLEX_SERVER_URL MAINTAINERR_JELLYFIN_SERVER_URL MAINTAINERR_QBITTORRENT_URL
export TRACEARR_URL TRACEARR_IMAGE TRACEARR_BIND_IP TRACEARR_PORT TRACEARR_AUTO_CONFIGURE TRACEARR_ADMIN_USERNAME TRACEARR_ADMIN_EMAIL TRACEARR_ADMIN_PASSWORD TRACEARR_CLAIM_CODE TRACEARR_PLEX_SERVER_URL TRACEARR_JELLYFIN_SERVER_URL TRACEARR_EMBY_SERVER_URL TRACEARR_DB_PASSWORD TRACEARR_POSTGRES_DATABASE TRACEARR_POSTGRES_USER TRACEARR_POSTGRES_PASSWORD TRACEARR_JWT_SECRET TRACEARR_COOKIE_SECRET TRACEARR_LOG_LEVEL TRACEARR_CORS_ORIGIN
export ENABLE_IMMICH IMMICH_URL IMMICH_BIND_IP IMMICH_WEB_PORT IMMICH_CONTAINER_PORT IMMICH_UPLOAD_LOCATION IMMICH_VERSION IMMICH_DB_USERNAME IMMICH_DB_DATABASE_NAME IMMICH_DB_PASSWORD IMMICH_DB_VECTOR_EXTENSION IMMICH_SERVER_IMAGE IMMICH_MACHINE_LEARNING_IMAGE
export ENABLE_ROMM GAMES_ROOT ROMM_URL ROMM_BIND_IP ROMM_WEB_PORT ROMM_CONTAINER_PORT ROMM_LIBRARY_ROOT ROMM_ASSETS_ROOT ROMM_CONFIG_ROOT ROMM_RESOURCES_ROOT ROMM_REDIS_DATA_ROOT ROMM_REDIS_HOST ROMM_REDIS_PORT ROMM_DB_DATA_LOCATION ROMM_DB_DRIVER ROMM_DB_HOST ROMM_DB_PORT ROMM_DB_NAME ROMM_DB_USER ROMM_DB_PASSWORD ROMM_DB_ROOT_PASSWORD ROMM_DB_QUERY_JSON ROMM_AUTH_SECRET_KEY ROMM_AUTO_CONFIGURE ROMM_ADMIN_USERNAME ROMM_ADMIN_EMAIL ROMM_ADMIN_PASSWORD ROMM_IGDB_CLIENT_ID ROMM_IGDB_CLIENT_SECRET ROMM_MOBYGAMES_API_KEY ROMM_SCREENSCRAPER_USER ROMM_SCREENSCRAPER_PASSWORD ROMM_RETROACHIEVEMENTS_API_KEY ROMM_STEAMGRIDDB_API_KEY ROMM_HASHEOUS_API_ENABLED ROMM_PLAYMATCH_API_ENABLED ROMM_LAUNCHBOX_API_ENABLED ROMM_FLASHPOINT_API_ENABLED ROMM_HLTB_API_ENABLED ROMM_IMAGE ROMM_DB_IMAGE

runtime_config_json="$(mktemp)"
node - "$runtime_config_json" <<'NODE'
const fs = require('node:fs');
const target = process.argv[2];
const keys = [
  'STACKARR_REPO_ROOT','TIMEZONE','PUID','PGID','MEDIA_ROOT','MUSIC_ROOT','DOWNLOADS_ROOT','BACKUP_ROOT','APP_ROOT','CONFIG_ROOT','STATE_ROOT','LOG_ROOT',
  'PLEX_CONFIG_PATH','PLEX_PREFS_PATH','PLEX_INSTALL_MODE','JELLYFIN_INSTALL_MODE','JELLYFIN_CONFIG_PATH',
  'ENABLE_4K_SERVARR','ENABLE_BAZARR','ENABLE_LIDARR','ENABLE_BOOKORBIT','ENABLE_IMMICH','ENABLE_ROMM','ENABLE_TINYMEDIAMANAGER','ENABLE_RECYCLARR','ENABLE_FLARESOLVERR',
  'ENABLE_TIDARR','ENABLE_SEERR','STACKARR_CONFIGURE_SEERR','ENABLE_PULSARR','ENABLE_MAINTAINERR','ENABLE_TRACEARR','ENABLE_BACKUP','USERNAME','PASSWORD','USER_EMAIL','PREFERRED_TORRENT_CLIENT',
  'SEERR_BIND_IP','PULSARR_BIND_IP','PULSARR_PORT','PULSARR_AUTHENTICATION_METHOD','PULSARR_COOKIE_SECURED',
  'MAINTAINERR_BIND_IP','MAINTAINERR_PORT','MAINTAINERR_BASE_PATH','MAINTAINERR_GITHUB_TOKEN','MAINTAINERR_CLEANUP_PRESETS',
  'TRACEARR_BIND_IP','TRACEARR_PORT','TRACEARR_AUTO_CONFIGURE','TRACEARR_ADMIN_USERNAME','TRACEARR_ADMIN_EMAIL','TRACEARR_ADMIN_PASSWORD','TRACEARR_CLAIM_CODE','TRACEARR_PLEX_SERVER_URL','TRACEARR_JELLYFIN_SERVER_URL','TRACEARR_EMBY_SERVER_URL','TRACEARR_DB_PASSWORD','TRACEARR_POSTGRES_DATABASE','TRACEARR_POSTGRES_USER','TRACEARR_POSTGRES_PASSWORD','TRACEARR_JWT_SECRET','TRACEARR_COOKIE_SECRET','TRACEARR_LOG_LEVEL','TRACEARR_CORS_ORIGIN',
  'TRANSMISSION_BIND_IP','TRANSMISSION_URL','TRANSMISSION_TORRENT_PORT','QBITTORRENT_BIND_IP','QBITTORRENT_URL',
  'QBITTORRENT_WEBUI_PORT','QBITTORRENT_TORRENT_PORT','PROWLARR_URL','PROWLARR_API_KEY','RADARR_URL','RADARR_API_KEY',
  'RADARR_4K_URL','RADARR4K_URL','RADARR4K_API_KEY','SONARR_URL','SONARR_API_KEY','SONARR_4K_URL','SONARR4K_URL',
  'SONARR4K_API_KEY','LIDARR_URL','LIDARR_API_KEY','BOOKORBIT_URL','BOOKORBIT_APP_URL','BOOKORBIT_CLIENT_URL','BOOKORBIT_BIND_IP','BOOKORBIT_WEB_PORT','BOOKORBIT_CONTAINER_PORT','BOOKS_ROOT','GAMES_ROOT','ROMM_URL','ROMM_BIND_IP','ROMM_WEB_PORT','ROMM_CONTAINER_PORT','ROMM_LIBRARY_ROOT','ROMM_ASSETS_ROOT','ROMM_CONFIG_ROOT','ROMM_RESOURCES_ROOT','ROMM_REDIS_DATA_ROOT','ROMM_REDIS_HOST','ROMM_REDIS_PORT','ROMM_DB_DATA_LOCATION','ROMM_DB_DRIVER','ROMM_DB_HOST','ROMM_DB_PORT','ROMM_DB_NAME','ROMM_DB_USER','ROMM_DB_PASSWORD','ROMM_DB_ROOT_PASSWORD','ROMM_DB_QUERY_JSON','ROMM_AUTH_SECRET_KEY','ROMM_AUTO_CONFIGURE','ROMM_ADMIN_USERNAME','ROMM_ADMIN_EMAIL','ROMM_ADMIN_PASSWORD','ROMM_IGDB_CLIENT_ID','ROMM_IGDB_CLIENT_SECRET','ROMM_MOBYGAMES_API_KEY','ROMM_SCREENSCRAPER_USER','ROMM_SCREENSCRAPER_PASSWORD','ROMM_RETROACHIEVEMENTS_API_KEY','ROMM_STEAMGRIDDB_API_KEY','ROMM_HASHEOUS_API_ENABLED','ROMM_PLAYMATCH_API_ENABLED','ROMM_LAUNCHBOX_API_ENABLED','ROMM_FLASHPOINT_API_ENABLED','ROMM_HLTB_API_ENABLED','ROMM_IMAGE','ROMM_DB_IMAGE','IMMICH_URL','IMMICH_BIND_IP','IMMICH_WEB_PORT','IMMICH_CONTAINER_PORT','IMMICH_UPLOAD_LOCATION','IMMICH_VERSION','IMMICH_DB_USERNAME','IMMICH_DB_DATABASE_NAME','IMMICH_DB_PASSWORD','IMMICH_DB_VECTOR_EXTENSION','STACKARR_DATABASE_MODE','DATABASE_IMAGE','DATABASE_PGDATA','DATABASE_BIND_IP','DATABASE_HOST_PORT','DATABASE_NAME','DATABASE_SUPERUSER','DATABASE_SUPERUSER_PASSWORD','REDIS_IMAGE','STACKARR_POSTGRES_DATABASE','STACKARR_POSTGRES_MAIN_DATABASE','STACKARR_POSTGRES_LOG_DATABASE','STACKARR_POSTGRES_USER','STACKARR_POSTGRES_PASSWORD','STACKARR_DATABASE_URL','STACKARR_LOG_DATABASE_URL','BOOKORBIT_DATABASE_URL','BOOKORBIT_POSTGRES_DATABASE','BOOKORBIT_POSTGRES_USER','BOOKORBIT_POSTGRES_PASSWORD','SEERR_DB_TYPE','SEERR_POSTGRES_DATABASE','SEERR_POSTGRES_USER','SEERR_POSTGRES_PASSWORD','PULSARR_DB_TYPE','PULSARR_DB_PATH','PULSARR_DB_HOST','PULSARR_DB_PORT','PULSARR_DB_NAME','PULSARR_DB_USER','PULSARR_DB_PASSWORD','PULSARR_POSTGRES_DATABASE','PULSARR_POSTGRES_USER','PULSARR_POSTGRES_PASSWORD','BAZARR_POSTGRES_ENABLED','BAZARR_POSTGRES_HOST','BAZARR_POSTGRES_PORT','BAZARR_POSTGRES_DATABASE','BAZARR_POSTGRES_USER','BAZARR_POSTGRES_PASSWORD','PROWLARR_POSTGRES_HOST','PROWLARR_POSTGRES_PORT','PROWLARR_POSTGRES_MAIN_DATABASE','PROWLARR_POSTGRES_LOG_DATABASE','PROWLARR_POSTGRES_USER','PROWLARR_POSTGRES_PASSWORD','RADARR_POSTGRES_HOST','RADARR_POSTGRES_PORT','RADARR_POSTGRES_MAIN_DATABASE','RADARR_POSTGRES_LOG_DATABASE','RADARR_POSTGRES_USER','RADARR_POSTGRES_PASSWORD','RADARR4K_POSTGRES_HOST','RADARR4K_POSTGRES_PORT','RADARR4K_POSTGRES_MAIN_DATABASE','RADARR4K_POSTGRES_LOG_DATABASE','RADARR4K_POSTGRES_USER','RADARR4K_POSTGRES_PASSWORD','SONARR_POSTGRES_HOST','SONARR_POSTGRES_PORT','SONARR_POSTGRES_MAIN_DATABASE','SONARR_POSTGRES_LOG_DATABASE','SONARR_POSTGRES_USER','SONARR_POSTGRES_PASSWORD','SONARR4K_POSTGRES_HOST','SONARR4K_POSTGRES_PORT','SONARR4K_POSTGRES_MAIN_DATABASE','SONARR4K_POSTGRES_LOG_DATABASE','SONARR4K_POSTGRES_USER','SONARR4K_POSTGRES_PASSWORD','LIDARR_POSTGRES_HOST','LIDARR_POSTGRES_PORT','LIDARR_POSTGRES_MAIN_DATABASE','LIDARR_POSTGRES_LOG_DATABASE','LIDARR_POSTGRES_USER','LIDARR_POSTGRES_PASSWORD','BOOKORBIT_JWT_SECRET','BOOKORBIT_SETUP_TOKEN','BAZARR_URL','SEERR_URL','SEERR_API_KEY','PULSARR_URL','PLEX_URL',
  'PLEX_TOKEN','JELLYFIN_URL','JELLYFIN_API_KEY','TINYMEDIAMANAGER_URL','FLARESOLVERR_URL','MAINTAINERR_URL','MAINTAINERR_PLEX_SERVER_URL','MAINTAINERR_JELLYFIN_SERVER_URL','MAINTAINERR_QBITTORRENT_URL','TRACEARR_URL',
  'BACKUP_TIME','BACKUP_SCHEDULE','BACKUP_WEEKDAY','BACKUP_RETENTION_COUNT','ENABLE_SCHEDULED_UPDATES','UPDATE_TIME','UPDATE_WEEKDAY','PLEX_BACKUP_MODE',
  'STACKARR_STORAGE_WAIT_SECONDS','STACKARR_API_KEY','STACKARR_DOCKER_CONTEXT','STACKARR_WEB_ENABLED','STACKARR_IMAGE','STACKARR_BIND_IP','STACKARR_WEB_PORT','STACKARR_TELEMETRY_FEATURE_ENABLED','STACKARR_TELEMETRY_ENABLED','STACKARR_TELEMETRY_ENDPOINT','STACKARR_TELEMETRY_CHANNEL','STACKARR_TELEMETRY_INGEST_KEY',
  'DOWNLOAD_INCOMPLETE_NAME','DOWNLOAD_COMPLETE_NAME','RADARR_CATEGORY','RADARR_4K_CATEGORY','SONARR_CATEGORY','SONARR_4K_CATEGORY',
  'LIDARR_CATEGORY','TRANSMISSION_IMAGE','QBITTORRENT_IMAGE','RADARR_IMAGE','SONARR_IMAGE','PROWLARR_IMAGE','BAZARR_IMAGE',
  'SEERR_IMAGE','PULSARR_IMAGE','MAINTAINERR_IMAGE','TRACEARR_IMAGE','RECYCLARR_IMAGE','FLARESOLVERR_IMAGE','LIDARR_IMAGE','BOOKORBIT_IMAGE','IMMICH_SERVER_IMAGE','IMMICH_MACHINE_LEARNING_IMAGE','ROMM_IMAGE','ROMM_DB_IMAGE','TIDARR_IMAGE','TINYMEDIAMANAGER_IMAGE',
  'PLEX_IMAGE','PLEX_DOCKER_PORT','JELLYFIN_IMAGE','JELLYFIN_DOCKER_PORT',
  'CLOUDFLARE_API_TOKEN','CLOUDFLARE_ACCOUNT_ID','CLOUDFLARE_ZONE_ID',
  'CLOUDFLARED_TUNNEL_NAME','CLOUDFLARED_TUNNEL_ID','CLOUDFLARED_METRICS_PORT','CLOUDFLARED_BIN',
  'CLOUDFLARED_TOKEN_FILE','CLOUDFLARED_KEEP_LAN','CLOUDFLARE_ROUTE_MANAGED','CLOUDFLARE_TUNNEL_ROUTES','CLOUDFLARE_ACCESS_ENABLED','CLOUDFLARE_ACCESS_ALLOWED_EMAILS','CLOUDFLARE_ACCESS_SESSION_DURATION','SEERR_ORIGIN_URL'
];
const config = Object.fromEntries(keys.map((key) => [key, process.env[key] ?? '']));
fs.writeFileSync(target, JSON.stringify(config));
NODE
STACKARR_DATABASE_FILE="$DB_FILE" node "$ROOT_DIR/scripts/runtime-config-write.cjs" "$runtime_config_json"
rm -f "$runtime_config_json"

RECYCLARR_FILE="$CONFIG_ROOT/recyclarr/recyclarr.yml"
if [[ ! -f "$RECYCLARR_FILE" ]]; then
    cat > "$RECYCLARR_FILE" <<EOF
# Stackarr manages Recyclarr config in ./configs/*.yml.
# This root file intentionally stays empty.
EOF
fi

ok "Wrote Stackarr runtime config to $DB_FILE"
ok "Created media, config, download, log, state, and backup folders"

echo ""
echo "Shared web credentials:"
echo "  Username: $USERNAME"
echo "  Password: $PASSWORD"
echo "  Stackarr API key: $STACKARR_API_KEY"
echo ""

if confirm "Enable login startup automation" yes; then
    "$ROOT_DIR/scripts/startup-install.sh" install --quiet
fi

if confirm "Enable scheduled backup automation" yes; then
    "$ROOT_DIR/scripts/backup-install.sh" install --quiet
fi

if confirm "Enable weekly update automation" no; then
    "$ROOT_DIR/scripts/update-install.sh" install --quiet
fi

echo ""
echo "Next steps:"
echo "  1. Run: bin/stackarr up"
echo "  2. Run: bin/stackarr configure"
echo "  3. Open Seerr on your LAN and complete the first-run admin flow"
echo "  4. Run: bin/stackarr configure --force to finish Seerr profile wiring"
echo "  5. Run: bin/stackarr db-info"
echo "  6. Optional remote access: brew install cloudflared"
echo "  7. Optional remote access: bin/stackarr cloudflare install --api-token <cloudflare-api-token> --route request.example.com=pulsarr"
echo "  8. Optional convenience: save Cloudflare route/API token settings in Stackarr to shorten the command"
echo "  9. Stackarr uses the Cloudflare API token to create the tunnel, DNS routes, and Access policies"
echo " 10. Use: bin/stackarr cloudflare start|stop|status|delete as needed after setup"
echo " 11. Without API automation, add a Published application route using HTTP -> http://127.0.0.1:5055"
echo " 12. Optional: add a Cloudflare Access app if you want an extra login layer before Seerr/Plex"
echo " 13. Optional maintenance: bin/stackarr update run"
echo " 14. Optional scheduling: bin/stackarr update install"
